### ISSUE TITLE
Refactor stash_utils submodule

### ISSUE THREAD

**Issue by truth-quark** [ACCESS-NRI/amami#22]
The `Stash` class in `stash_utils.py` adds another object layer for accessing the `ATM_STASHLIST` lookup. This has a few problems:
* It introduces another layer of indirection
* New `Stash` instances are created every time a code is looked up.

Ideally, `Stash` should be refactored to a dict for simplification & provide a common Pythonic interface. Each code lookup should return an existing `ATM_STASHLIST` entry, negating the need to create a new `Stash` record object.

Tasks:
* ~~Refactor `amami/stash_utils/__init__.py` to `amami/stash.py` (package to simple module)~~ (see #20)
* Refactor `Stash` class:
  - Modify `Stash` class to inherit from `UserDict`
  - Implement custom `__getitem__`, `__setitem__` to convert `str`, stash codes etc to `int` keys
  - Remove unused methods
  - Change `ATM_STASHLIST` to instance of the new Stash dict type
  - Refactor calling code to directly reference the lookup 
  - Idea: use dicts or named tuples for the values?

More ideas (see #33):
* ~~Move `Stash` lookup into `um_utils` module as it's part of unified model code~~
* ~~Delete the `stash_utils` module~~

**Comment by atteggiani** [comment]
> Refactor `Stash` class & `ATM_STASHLIST` to dict lookup (avoid `Stash` obj creation to convert/look up codes)

`ATM_STASHLIST` is already a dictionary. How do you want to refactor it?
I haven't well understood the picture of the new structure you have in mind.

> * Implement custom `__getitem__`, `__setitem__` to work with `str`, stash codes etc

In the point below you mentioned removing the `Stash` class. Where do you want to implement the custom `__getitem__` and `__setitem__` methods?

> * Remove existing `Stash` class, use `dict` interface for standard python interoperability

Not sure why you want to remove the `Stash` class. I believe having a STASH object is useful in many different subcommands (future ones as well).

> * Move lookup to `um_utils` module as it's part of unified model code

We could move the `Stash` class to the `um_utils` module.

But I still haven't really understood the structure of such 'lookup' you refer to.

> * Delete the `stash_utils` module

This can be done If we move the `Stash` class to the `um_utils` module.

**Comment by truth-quark** [comment]
> > Refactor `Stash` class & `ATM_STASHLIST` to dict lookup (avoid `Stash` obj creation to convert/look up codes)
> 
> `ATM_STASHLIST` is already a dictionary. How do you want to refactor it? I haven't well understood the picture of the new structure you have in mind.
> 
> > * Implement custom `__getitem__`, `__setitem__` to work with `str`, stash codes etc
> 
> In the point below you mentioned removing the `Stash` class. Where do you want to implement the custom `__getitem__` and `__setitem__` methods?

Ooops, I mucked up the original ticket text. This should be fixed, explaining refactoring the `Stash` class into a customised `dict` for the ATM list.

I'm currently working on an example of the above work in another branch...

**Comment by atteggiani** [comment]
Captured refactoring of stash_utils in [#20](https://github.com/ACCESS-NRI/amami/issues/20)

**Comment by truth-quark** [comment]
I'll reopen as it covers refactoring the custom `Stash`class (which needs some tweaks to bring in line with Python conventions).

**Comment by atteggiani** [comment]
@truth-quark 
Please edit the body of the issue:
- to cover only the refactoring of the Stash class (without including the package to simple module refactor already mentioned in #20)
- to list specific modifications that you think need to put in place for the Stash class

**Comment by truth-quark** [comment]
I've updated the issue/crossed out the structural changes from #33.

The class modifications needs more thought, so I'll update that after another code experiment.
